server:
  debug: true
  port: 80
  proxy: http://localhost:10880
  auth_header: "Bearer token"
  timeout: 5s

search:
  - name: 百度
    domain: www.baidu.com
    weight: 1
    positionWeight: 1
    score: 10
    enable: true
  - name: Bing
    domain: cn.bing.com
    weight: 1
    positionWeight: 1
    score: 10
    enable: true
  - name: Google
    domain: www.google.com
    weight: 1
    positionWeight: 1
    score: 10
    enable: true
    proxy: http://localhost:10880
  - name: 微信公众号
    domain: weixin.sogou.com
    weight: 1
    positionWeight: 1
    score: 10
    enable: true

site:
  - domain: zhuanlan.zhihu.com
    weight: 5
    score: 1
  - domain: github.com
    weight: 3
    score: 1
  - domain: juejin.cn
    weight: 2
    score: 1
  - domain: www.csdn.com
    weight: 1
    score: 1
  
